baseURL = "https://luxstories.github.io/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Lukas Samael"
# copyright = "Copy, _right_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Lukas Samael"
  headline = "An owner of Lux-Awesomes"
  image = "https://upld.zone.id/uploads/3fiqg9qiq/logo.webp"  # path relative to static directory

  links = [
    { email = "mailto:drsatanic@hotmail.com" },
    { link = "https://luxstories.github.io/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
    { bluesky = "https://bsky.app/profile/lukasamael" },
    # { codepen = "https://codepen.io/username" },
    { dev = "https://dev.to/luxstreamer" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/luxstories" },
    { gitlab = "https://gitlab.com/luxstories" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    { mastodon = "https://mstdn.plus/@thesmoshq" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    { twitter = "https://twitter.com/thesmoshq" },
    # { whatsapp = "https://wa.me/phone-number" },
    { x = "https://x.com/thesmoshq" },
    # { youtube = "https://youtube.com/username" },
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.86.1"
